### PR TITLE
Refactor project tree

### PR DESCRIPTION
**Pull request by chrichri17**
This PR :
- rename the `scripts` folder into `lib`
- creates a `views` folder to hold all the views of our application. A view is basically a high level component that you import in `views/routes.ts`
- moves `routes.ts` and `router.ts` from `scripts` to `views` since they are related to views
- delete the `Main.vue` component. This component does nothing and it's neither an atomic component nor a real view. So...

Do you suggest any other change ?

### CODE REVIEW

**Comment by chrichri17** [comment]
Current dependencies on/for this PR:
* main
  * **PR #9** <a href="https://app.graphite.dev/github/pr/YacineSteeve/quizoot/9" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/YacineSteeve/quizoot/9?utm_source=stack-comment).

**Comment by YacineSteeve** [comment]
I have a suggestion for the tree:

Instead of 

```
...
|__views
   |__Home.vue
   |__router.ts
   |__routes.ts
```
we can do:
```
...
|__views
|  |__Home.vue
|  |__Contact.vue
|  |__ ...
|__router
   |__index.ts (router.ts + routes.ts)
```

As here

Tree

**Comment by chrichri17** [comment]
I knew you would said that. I was going to suggest the same except that I don't want a router folder lol. How about we do as you suggested but we use a single file called router.ts ?

**Comment by YacineSteeve** [comment]
Nice, I'm okay 😂

**Pull request merged**
