### PR TITLE
Add a progress bar for questions

### PR DESCRIPTION
**Pull request by YacineSteeve**
Here is what it looks like:
<br>
1. On desktop

<br>
 2. On mobile
<br><br>

### CODE REVIEW

**Comment by YacineSteeve** [comment]
Current dependencies on/for this PR:
* main
  * **PR #82** <a href="https://app.graphite.dev/github/pr/YacineSteeve/quizoot/82" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/YacineSteeve/quizoot/82?utm_source=stack-comment).

**Comment by chrichri17** [comment]
Although it looks awesome, what would happen if a quiz has 35 questions ?🙂

I guess it won't look good anymore. Especially for the mobile version.

Isn't that right ?

**Comment by YacineSteeve** [comment]
> Although it looks awesome, what would happen if a quiz has 35 questions ?🙂

Why would a quiz have 35 questions?! 😭🤣

**Comment by chrichri17** [comment]
You don't know the future. It might be an exam of 4 hours 🫣

**Comment by YacineSteeve** [comment]
> I guess it won't look good anymore. Especially for the mobile version.

You're absolutely right, though.
Do you suggest I drop the progress bar? 

I could anyway find a trick to manage greater number of questions.

**Comment by chrichri17** [comment]
I was thinking about a simple progress bar. Just a line with a percentage of it colored. But yeah we can just drop it.

**Comment by YacineSteeve** [comment]
> You don't know the future. It might be an exam of 4 hours 🫣

Wow!😂

**Comment by YacineSteeve** [comment]
> I was thinking about a simple progress bar. Just a line with a percentage of it colored.

That's what I thought about at first. But with the presence of Question i/N, this style seemed a bit useless. 

> But yeah we can just drop it.

Okay then. Goodbye, beautiful progress bar.

**Comment by chrichri17** [comment]
> Okay then. Goodbye, beautiful progress bar.

🪦 rip

**Pull request closed without merging**
